# AWS credentials and info
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-access-key: ${SECRET_ACCESS_KEY}
    region:
      static: ${REGION}
    stack:
      auto: false

# Bucket info
application:
  bucket:
    name: ${BUCKET_NAME}

# Spring and db info
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Application port
server:
  port: ${PORT}
